In [2]:
import numpy as np

In [5]:
A = np.array([[1,77,3],[4,5,6],[7,8,9]])
B = np.linspace(5,30,6).reshape(3,2)

In [6]:
B

array([[ 5., 10.],
       [15., 20.],
       [25., 30.]])

In [7]:
A

array([[ 1, 77,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [8]:
np.matmul(A,B)

array([[1235., 1640.],
       [ 245.,  320.],
       [ 380.,  500.]])